version: 2

models:
  - name: c_ride_entity
    description: Cleaned ride entity table with Ride information; - local time added; numeric formats are aligned with 2 decimals, only those fields which are majorly used.  
    columns:
      - name: ride_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: ride_status
        tests:
          - not_null
      - name: create_time_utc
        description: primary key
        tests:
          - not_null
      - name: drof_off_time_utc
        description: primary key
        tests:
          - not_null
 