version: 2

models:
  - name: ride_entity_cleansed
    description: Ride information; one row is one ride
    columns:
      - name: ride_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: ride_status
        tests:
          - not_null
      - name: create_time_utc
        description: primary key
        tests:
          - not_null
 